import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

import { AppTopbar } from "@/components/app-topbar";
import { DynamicBreadcrumb } from "@/components/dynamic-breadcrumb";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body className={`${inter.variable} antialiased min-h-screen flex flex-col bg-zinc-50 dark:bg-[#09090b] transition-colors duration-300`}>
        <AppTopbar />
        <div className="md:px-8 px-4 pt-4 max-w-[1600px] mx-auto w-full">
          <DynamicBreadcrumb />
        </div>
        <main className="flex-1 flex flex-col relative">
          {children}
        </main>
      </body>
    </html>
  );
}
